{% set name = "aiofile" %}
{% set version = "3.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiofile-{{ version }}.tar.gz
  sha256: e5ad718bb148b265b6df1b3752c4d1d83024b93da9bd599df74b9d9ffcf7919b

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv

requirements:
  host:
    - pip
    - python
    - poetry-core >=1
  run:
    # Conda version of ~=0.9.0
    - caio >=0.9.0,<10
    - python

test:
  imports:
    - aiofile
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mosquito/aiofile
  summary: Asynchronous file operations.
  description: Real asynchronous file operations with asyncio support.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENCE
  dev_url: https://github.com/mosquito/aiofile
  doc_url: https://github.com/mosquito/aiofile

extra:
  recipe-maintainers:
    - BastianZim
